// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16/04/2025, 09:10:03
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["I:/Documents/project-repos/tech-test-2/movie-db/components/**/*.{vue,js,jsx,mjs,ts,tsx}","I:/Documents/project-repos/tech-test-2/movie-db/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","I:/Documents/project-repos/tech-test-2/movie-db/components/**/*.{vue,js,jsx,mjs,ts,tsx}","I:/Documents/project-repos/tech-test-2/movie-db/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","I:/Documents/project-repos/tech-test-2/movie-db/plugins/**/*.{js,ts,mjs}","I:/Documents/project-repos/tech-test-2/movie-db/composables/**/*.{js,ts,mjs}","I:/Documents/project-repos/tech-test-2/movie-db/utils/**/*.{js,ts,mjs}","I:/Documents/project-repos/tech-test-2/movie-db/pages/index.vue","I:/Documents/project-repos/tech-test-2/movie-db/pages/movies.vue","I:/Documents/project-repos/tech-test-2/movie-db/pages/series.vue","I:/Documents/project-repos/tech-test-2/movie-db/pages/contact.vue","I:/Documents/project-repos/tech-test-2/movie-db/pages/details/[id].vue","I:/Documents/project-repos/tech-test-2/movie-db/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","I:/Documents/project-repos/tech-test-2/movie-db/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","I:/Documents/project-repos/tech-test-2/movie-db/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;